config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pianos
  get "/confirmation_creation" => "pianos#confirmation_creation"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/piano.rb
class Piano < ApplicationRecord
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pianos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/pianos_controller.rb
class PianosController < ApplicationController

   before_action :find_piano, only: [:show, :edit, :update, :destroy, :confirmation_creation]

   def index
     @pianos = Piano.all
     @gmap = "https://maps.googleapis.com/maps/api/js?key=" + ENV["GMAP_KEY"]
   end

  def show
    @gmap = "https://maps.googleapis.com/maps/api/js?key=" + ENV["GMAP_KEY"]
  end

   def new
     @piano= Piano.new
   end

   def create
     @piano = Piano.new(piano_params)
     @piano.user = current_user
     if @piano.save
       redirect_to confirmation_creation_path(id: @piano.id)
     else
       render :new
     end
   end

   def edit
   end

   def update
     if (@piano.user == current_user) && @piano.update(piano_params)
         #attention le update ci-dessus est le update de active record, pas la méthode update du controleur
       redirect_to confirmation_creation_path(id: @piano.id)
     else
       render :edit
     end
   end

   def destroy
     if @piano.user == current_user
       @piano.destroy
       redirect_to pianos_path(user_id: current_user.id)
     else
       flash[:alert] = "You can't delete this product"
     end
   end

   def confirmation_creation
   end

   def research
    if params[:piano]
       @pianos = Piano.select{|piano| (piano.brand.downcase == params[:piano][:brand].downcase)}
     else
       @pianos =[]
     end
   end

   private
   def piano_params
     params.require(:piano).permit(:brand, :address)
   end

   def find_piano
     @piano = Piano.find(params[:id].to_i)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pianos_helper.rb
module PianosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pianotramp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>Pianotramp</h1>
    <p>A piano everywhere, everytime !</p>

    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-4"></div>
        <div class="col-xs-12 col-sm-4"></div>
        <div class="col-xs-12 col-sm-4"></div>
        <%= link_to "Start now!", pianos_path, class:"btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>

</div>

app/views/pianos/_form.html.erb
<%= simple_form_for @piano do |f| %>
  <%= f.input :brand, placeholder: "Yamaha C1 Silent", error: 'Company name is mandatory, please specify one' %>
  <%= f.input :address, placeholder: "133 avenue du Faubourg Saint-Honoré", label:"Address" %>
  <%= f.button :submit, "Submit", class: "btn btn-primary" %>
<% end %>

app/views/pianos/_listing.html.erb
<% @pianos.each do |piano| %>
  <%= link_to piano_path (piano) do %>
    <div class="card">
      <div class="card-category">Popular</div>
      <div class="card-description">
        <h3><%= piano.brand %></h2>
        <p>address : <i><%=piano.address %></p>
      </div>
      <%= image_tag 'user.jpg', class: "card-user avatar"%>
    </div>
  <%end %>
<% end %>

app/views/pianos/confirmation_creation.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h1 class="text-center">
        Your new piano for <%= @piano.brand %> has been successfully uploaded !
      </h1>
      <ul>
        <li>
          <p>type: <%= @piano.brand %></p>
        </li>
        <li>
          <p>address: <%= @piano.brand %></p>
        </li>
          <p>latitude: <%= @piano.latitude %>; longitude: <%= @piano.longitude %></p>
        </li>
      </ul>
      <p class="text-center">
        <%= link_to "View Piano Description", piano_path(@piano), class: "btn btn-success" %>
      </p>
    </div>
  </div>
</div>

app/views/pianos/edit.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h1 class="text-center">
      Modify the investor presentation
    </h1>
    <%= render "form" %>
    </div>
  </div>
</div>

app/views/pianos/index.html.erb
<div class="container">
 <h2>voici la liste des pianos</h2>
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <%= render "listing" %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div id="map" style="width: 100%; height: 400px;">
      </div>
      <script type="text/javascript" src=<%= @gmap %> ></script>

      <script type="text/javascript">

        var latitude =  48.8609573 ;
        var longitude = 2.32164548 ;

        var myLatlng = new google.maps.LatLng(latitude,longitude);


        var myOptions = {
            zoom: 12,
            center: myLatlng,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            styles: []
        };

        var map = new google.maps.Map(document.getElementById('map'), myOptions);

        <% @pianos.each do |piano| %>
          var latitude =  <%= piano.latitude %> ;
          var longitude = <%= piano.longitude %> ;
          var Latlng = new google.maps.LatLng(latitude, longitude);

          var marker = new google.maps.Marker({
                position: Latlng,
                map: map,
            });
        <% end %>

      </script>
    </div>
  </div>


</div>

app/views/pianos/new.html.erb
<div class="padded"></div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <h1 class="text-center">
      Create a new piano
    </h1>

    <%= render "form" %>


    </div>
  </div>
</div>

app/views/pianos/show.html.erb
<%= javascript_tag do %>
  window.latitude = "<%=j @piano.latitude.to_s %>";
  window.longitude = "<%=j @piano.longitude.to_s %>";
  window.gmap = "<%=j @gmap %>";
<% end %>

<div class="container">
  <div class="padded">
  </div>

  <div class="media-aside">
    <div class="row">

      <div class="media-section col-xs-12 col-sm-6">
        <h1><%= @piano.brand%></h1>
        <h5> Last update : <%= @piano.updated_at %> </h5>
        <h6> address: <%= @piano.address %></h6>
        <% if @piano.user == current_user %>
          <%= link_to "Modify", edit_piano_path, class: "btn btn-warning" %>
          <%= link_to "Delete", piano_path(@piano), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-6">

        <div id="map" style="width: 100%; height: 400px;">
        </div>

        <script type="text/javascript" src=<%= @gmap %> ></script>

        <script type="text/javascript">

          var latitude = <%= @piano.latitude %>;
          var longitude = <%= @piano.longitude %>;

          var myLatlng = new google.maps.LatLng(latitude,longitude);


          var myOptions = {
              zoom: 14,
              center: myLatlng,
              mapTypeId: google.maps.MapTypeId.ROADMAP,
              styles: []
          };

          var map = new google.maps.Map(document.getElementById('map'), myOptions);
          var marker = new google.maps.Marker({
              position: myLatlng,
              map: map,
              title: "You are here!"
          });
        </script>

      </div>
    </div>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>

    <%= link_to root_path do %>
      <%= image_tag "en.png" %>
    <% end %>
    <%= link_to root_path do %>
      <%= image_tag "fr.png" %>
    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>